[SERVICE]
    Flush         1
    Daemon        Off
    Log_Level     info
    Parsers_File  parsers.conf

[INPUT]
    Name              tail
    Path              /var/lib/docker/containers/*/*.log
    Parser            docker
    Tag               docker.*

    Refresh_Interval  5
    Mem_Buf_Limit     5MB
    Skip_Long_Lines   On
    
[FILTER]
    Name    record_modifier
    Match   docker.*
    Record  service rag-api
    Record  environment local
    Record  platform docker

[OUTPUT]
    Name              loki
    Match             docker.*
    Host              loki
    Port              3100
    Labels            job=fluent-bit
    Label_Keys        $service,$environment
    Line_Format       json
    Auto_Kubernetes_Labels off
