apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rag-api
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app: rag-api
    environment: production

spec:
  project: default

  source:
    repoURL: https://github.com/abdulmuhd-dev/RAG-system
    targetRevision: main
    path: k8s
    directory:
      exclude: "argocd-app.yml"

  destination:
    server: https://kubernetes.default.svc
    namespace: rag-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - ServerSideApply=true

    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
