apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets
  namespace: external-secrets
  annotations:
    # gets permission to read Secrets Manager
    eks.amazonaws.com/role-arn: >
      arn:aws:iam::617711905688:role/rag-system-external-secrets-role
